### ISSUE TITLE
would be nice to make midisettings less verbose

### ISSUE THREAD

**Issue by avilleret** [iem-projects/pd-mediasettings#2]
midi settings print lots of things in pd console when listing devices
that might be relevant for debugging purpose, but it would be nice to shut it up in normal use
maybe with a verbose message to set verbosity of by using Pd log level

**Comment by umlaeute** [comment]
are you talking about printouts like the following, or something else?

~~~
=================================<
alsamidi: 2 1
>=================================
~~~
